### ISSUE TITLE
Error: MissingMethodException

### ISSUE THREAD

**Issue by Hona** [GetoXs/MediatR.Extensions.FluentValidation.AspNetCore#10]
Packages installed:

* .NET 6 Preview
* FluentValidation 10.3.3
* MediatR.Extensions.FluentValidation.AspNetCore 1.2.0

```cs
var applicationAssembly = typeof(CreateUserValidator).Assembly;

services.AddMediatR(applicationAssembly);
services.AddFluentValidation(new []{ applicationAssembly });
```

```
System.MissingMethodException: Method not found: 'FluentValidation.AssemblyScanner FluentValidation.AssemblyScanner.FindValidatorsInAssembly(System.Reflection.Assembly)'.
   at FluentValidation.ServiceCollectionExtensions.AddValidatorsFromAssembly(IServiceCollection services, Assembly assembly, ServiceLifetime lifetime, Func`2 filter)
   at FluentValidation.ServiceCollectionExtensions.AddValidatorsFromAssemblies(IServiceCollection services, IEnumerable`1 assemblies, ServiceLifetime lifetime, Func`2 filter) in C:\Projects\FluentValidation\src\FluentValidation.DependencyInjectionExtensions\ServiceCollectionExtensions.cs:line 36
   at MediatR.Extensions.FluentValidation.AspNetCore.ServiceCollectionExtensions.AddFluentValidation(IServiceCollection services, IEnumerable`1 assemblies, ServiceLifetime lifetime, Func`2 filter)
   at ...
```

**Comment by GetoXs** [comment]
Have you tried with official .net 6.0? I have tested it locally and do not see any issues. 
Beside that I have added nests for .net6 https://github.com/GetoXs/MediatR.Extensions.FluentValidation.AspNetCore/commit/31289a92efc0f65f2aa267d40717c931980d7265
