### ISSUE TITLE
Package breaks with FluentValidation v 11

### ISSUE THREAD

**Issue by mchaseleaf** [GetoXs/MediatR.Extensions.FluentValidation.AspNetCore#13]
MediatR.Extensions.FluentValidation.AspNetCore is broken with FluentValidation version 11. It worked fine in FluentValidation version 10. However, after upgrading to 11.0.1, the application breaks on start throwing the following exception from service.AddFluentValidation:

System.MissingMethodException
HResult=0x80131513
Message=Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection FluentValidation.ServiceCollectionExtensions.AddValidatorsFromAssemblies(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Collections.Generic.IEnumerable1<System.Reflection.Assembly>, Microsoft.Extensions.DependencyInjection.ServiceLifetime, System.Func2<AssemblyScanResult,Boolean>)'.
Source=MediatR.Extensions.FluentValidation.AspNetCore
StackTrace:
at MediatR.Extensions.FluentValidation.AspNetCore.ServiceCollectionExtensions.AddFluentValidation(IServiceCollection services, IEnumerable1 assemblies, ServiceLifetime lifetime, Func2 filter)
at Api.Startup.ConfigureServices(IServiceCollection services) in C:[project folder omitted]\Startup.cs:line 100
at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.g__Startup|0(IServiceCollection serviceCollection)
at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.b__0(IServiceCollection services)
at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.b__0(HostBuilderContext context, IServiceCollection services)
at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
at Microsoft.Extensions.Hosting.HostBuilder.Build()
at Api.Program.Main(String[] args) in C:[project folder omitted]\Program.cs:line 12

I opened a bug with FluentValidation, but they closed it saying this is a problem with  MediatR.Extensions.FluentValidation.AspNetCore. You can see that issue here for reference: https://github.com/FluentValidation/FluentValidation/issues/1939 

They say you will "need to publish a new version of this package that’s compatible with FluentValidation 11 (they should just need to recompile targeting FV 11). They should also ensure that they lock their dependency versions in line with SemVer to not auto upgrade across major versions to prevent issues like this in the future."

**Comment by GetoXs** [comment]
Hi @mchaseleaf what version of `MediatR.Extensions.FluentValidation.AspNetCore` do you use? 
I have tested last [version 2.0.0](https://www.nuget.org/packages/MediatR.Extensions.FluentValidation.AspNetCore/2.0.0) with FluentValidation v.11 and everything works. 
Please keep in mind that I've released new version on January to be valid with v.10. Isuee: https://github.com/GetoXs/MediatR.Extensions.FluentValidation.AspNetCore/issues/11

**Comment by JeremySkinner** [comment]
For some additional context this is because of this line: https://github.com/GetoXs/MediatR.Extensions.FluentValidation.AspNetCore/blob/master/src/MediatR.Extensions.FluentValidation.AspNetCore/ServiceCollectionExtensions.cs#L20

...we added some optional parameters to this method in v11 which are a binary breaking change meaning you can't just swap out the FV10 binaries for FV11, and requires a recompile or you'll get missing method exceptions like this. I'd generally recommend adding an upper-version constraint to your dependency too, as otherwise Nuget will silently allow upgrades across major version boundaries (even though this isn't correct from a SemVer perspective).

**Comment by mchaseleaf** [comment]
I have MediatR 10.0.1, MediatR.Extensions.Microsoft.DependencyInjection 10.0.1, and MediatR.Extensions.FluentValidation.AspNetCore 2.0.0. This is in .NET 6.0 also, if that matters.

**Comment by GetoXs** [comment]
@JeremySkinner thanks for detailed explanation. I have just noticed cross-version failures on CI https://github.com/GetoXs/MediatR.Extensions.FluentValidation.AspNetCore/runs/6357867530?check_suite_focus=true

@mchaseleaf I have just released version 3.0 with compatible with FV 11.x https://www.nuget.org/packages/MediatR.Extensions.FluentValidation.AspNetCore/3.0.0

**Comment by mchaseleaf** [comment]
Thanks. It builds and runs with FV11, and I believe it is working as expected!
